cs4500-sp19-nowayjose/cs4500-sp19-client-react-nowayjose

src/services/FAQService.js
=> Faq service

package-lock.json, package.json, src/components/Admin.js, src/components/ServiceQuestion.js, src/services/ServiceQuestionService.js
Implement the service questions list and javascript service
=> Service questions list

src/components/ServiceQuestion.js
Title for service questions was accessing the wrong field of the returned JSON
=> Fix the title of service questions

src/services/ServiceAnswerService.js
=> removed localhost for url

package-lock.json, src/components/Admin.js, src/components/FaqAnswers.js, src/services/FAQAnswerService.js
=> Faq answer screen

src/services/FAQAnswerService.js
fixed request to point to prod
=> Fixed faq answer service calls

package-lock.json, src/components/Admin.js, src/components/FAQDetails.js, src/components/FAQs.js
Added support to navigate to details page
=> Navigate faq details

src/components/Admin.js, src/components/ServiceDetails.js, src/components/Services.js, src/services/ServiceService.js
This PR adds CRUD operations for services and service details.
=> Add CRUD for Services and Service Details

src/components/Admin.js, src/components/ServicesContainer.js, src/components/ServicesList.js
> User interface components are easier to test when they are not tightly coupled to other components and do not maintain their own state. Refactor at least one component implemented in earlier sprints as a stateless component to make it unit test friendly. The component should be re-implemented as a function accepting as argument the data to be rendered as well as event handlers bound in the component's HTML elements. The refactoring might entail creating a container component. If you are familiar with redux, feel free to use it instead or in addition. Create a story documenting the component being refactored. Include a link to the PR listing all files changed/added to accomplish the refactoring. Include a link to the story in the individual level story assigned to the TA.
=> Refactor services component to be stateless

src/data/services.mock.json
> Create at least one mock data file to be used to test the component refactored above. Use data retrieved from a REST service as an example of the content of the mock data file. The file should be formatted as a JSON file and added white spaces for easy readability. Name the files using the pattern <table>.mock.json where <table> is the name of the table or entity from which the data came from. If several developers share the same mock data, collaborate with them to agree on its content. Add the files to source control and document the work in a story. Include the PR in the story and share a link to the story in the individual level story assigned to the TA.
=> Add mock service data

src/data/serviceQuestions.mock.json
creating mock data for service questions
=> added mock data for servicequestion

package-lock.json, package.json, src/components/ServiceAnswer/__snapshots__/answerTable.test.js.snap, src/components/ServiceAnswer/answerTable.test.js, src/components/ServiceAnswer/index.js
=> Snapshot tests for service answers

src/components/ServiceDetails.js, src/services/Service.test.js, src/services/ServiceService.mock.js
>Mock at least one service. Mock the service used by the component(s) refactored earlier. The mocked service should isolate components from needing remote resources such as RESTful services. If several developers share the same service, collaborate to agree which part of the mock service to implement, e.g., one developer might work on the finder methods and another developer might work on the create and update methods. Check in the files and document the work in a story. Include the PR in the story and share a link to the story in the individual level story assigned to the TA.
>Create at least one test suite that demonstrates programmatic page layout validation. Add classes to HTML elements to be tested such as fields, buttons, line items, table rows, etc. The tests should validate the …
=> Add service tests

src/services/ServiceService.mock.js
> Mock at least one service. Mock the service used by the component(s) refactored earlier. The mocked service should isolate components from needing remote resources such as RESTful services. If several developers share the same service, collaborate to agree which part of the mock service to implement, e.g., one developer might work on the finder methods and another developer might work on the create and update methods. Check in the files and document the work in a story. Include the PR in the story and share a link to the story in the individual level story assigned to the TA.
=> Add mock service

src/data/users.mock.json, src/services/UserService.mock.js
Mock at least one service. Mock the service used by the component(s) refactored earlier. The mocked service should isolate components from needing remote resources such as RESTful services. If several developers share the same service, collaborate to agree which part of the mock service to implement, e.g., one developer might work on the finder methods and another developer might work on the create and update methods. Check in the files and document the work in a story. Include the PR in the story and share a link to the story in the individual level story assigned to the TA.
=> Create mock UserService

package.json, src/App.js, src/components/Home.js, src/components/SearchBar/SearchBar.js
This PR adds a home screen with a search bar. Attached is a screen shot below.
@cs4500-sp19-nowayjose/team-2 @cs4500-sp19-nowayjose/team-3
**Please update the home screen routes when your components are ready!**
=> Add home screen with search bar

src/App.js, src/components/Login/Login.js, src/containers/LoginContainer.js, src/services/UserService.js
=> Login screen

src/App.js, src/components/Provider/Provider.js, src/components/Provider/Rating.js, src/components/Provider/Review.js
This PR adds reviews to the provider screen.
=> Add reviews to provider screen

src/App.js, src/components/Provider/FAQ.js, src/components/Provider/Provider.js, src/components/Provider/Rating.js, src/components/Provider/Review.js
This PR adds faqs to the provider screen.
=> Add faqs to the provider screen.

src/components/UsersContainer.js, src/components/UsersList.js
**Pagination Demo:**
**Search Demo:**
=> Create user pagination and search for admin

src/components/BusinessScreen/__snapshots__/businessForm.test.js.snap, src/components/BusinessScreen/businessForm.js, src/components/BusinessScreen/businessForm.test.js, src/containers/BusinessInfoContainer.js
added snapshot testing for business form
=> added snapshot testing

src/components/ServiceDetails.js, src/services/ServiceCategoryService.js, src/services/ServiceService.js, src/services/UserService.js
**Option to select category for service in Admin portal**
**Success!**
=> create service-serviceCategory relationship

src/components/ServiceCategoriesContainer.js, src/components/ServiceCategoriesList.js
**Without filter:**
**With filter:**
=> create search functionality for service category
